### ISSUE TITLE
Improve the build scripts

### ISSUE THREAD

**Issue by prologic** [troglobit/troglos#1]
I don't suppose you have a bit of spare time to improve the build scripts? Right now they assume a few too many things. I made some changes to try and reproduce what you've done and build troglos on my local system but ran into many failures.

I'd like to play around with troglos for an x86_86 target (my host is x86_64) so I'm not even sure a custom toolchain is required really -- but you do this thing the build scripts `@cp /path/to/lib/* /target/path/to/lib` -- I'm not even sure what this is trying to do :)

**Comment by troglobit** [comment]
Oh dear, how did I ever miss this bug report? :confused: 

I had a plan initially to decouple the target system and toolchain from the build scripts. Time caught up with me however, so that is yet to happen. 

The bizarre copy operation in the main Makefile was a crude way of copying the Debian/Ubuntu cross-toolchains's C library (and other helper libs) to the target staging area before creating the ramdisk.

**Comment by troglobit** [comment]
Support for multiple targets is now on master, since Nov 13 2016, commit accf163.  Currently ARM/Versatile and PowerPC/ppce500 targets are supported, but x86_64 and aarch64 support is on the way as well.

Make sure to use a crosstool-NG based toolchain, e.g. one from [my FTP](http://ftp.troglobit.com/pub/Toolchains/), since that is required these days.
